name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Login to dockerhub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-cicd .
    - name: Publish docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-cicd:latest
  
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Login to dockerhub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Pull docker image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-cicd:latest
    - name: Run docker container
      run: docker run -d -p 8900:8900 -e MONGO_PASSWORD=${{ secrets.MONGODB_PASSWORD }} ${{ secrets.DOCKER_USERNAME }}/nodejs-cicd